export const FETCH_COUNTRY = "FETCH_COUNTRY";
export const FETCH_COUNTRY_SUCCESS = "FETCH_COUNTRY_SUCCESS";
export const FETCH_COUNTRY_ERROR = "FETCH_COUNTRY_ERROR";
//search countries
export const SEARCH_COUNTRIES = "SEARCH_COUNTRIES";
export const SEARCH_COUNTRIES_SUCCESS = "SEARCH_COUNTRIES_SUCCESS";
export const SEARCH_COUNTRIES_ERROR = "SEARCH_COUNTRIES_ERROR";
//fetch countries
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_ERROR = "FETCH_COUNTRIES_ERROR";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
//filter countries
export const FILTER_COUNTRIES = "FILTER_COUNTRIES";
export const FILTER_COUNTRIES_SUCCESS = "FILTER_COUNTRIES_SUCCESS";
export const FILTER_COUNTRIES_ERROR = "FILTER_COUNTRIES_ERROR";
